import Head from "next/head";
import Home_page from "../src/components/home/home_page";
import styles from "../styles/Home.module.css";
export default function Home({ title, data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Next Js </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home_page data={data} title={title} />
      <p>that is easy simple</p>
    </div>
  );
}

export async function getServerSideProps() {
  // we can just import it from internal resource
  const { events_categories } = await import("/data/data.json");

  return {
    props: {
      title: "Home Page Coming Events",
      data: events_categories,
    },
  };
}
